server:
  port: 8081

spring:
  application:
    name: user-service
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

# spring.datasource.url: jdbc:sqlserver://localhost;databaseName=jimmap_db
# spring.datasource.username: jerry
# spring.datasource.password: 123456

# spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
# spring.jpa.hibernate.ddl-auto: update